config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Chat::Engine => "/chat", as: "chat"
  root to: "home#index", id: "home"

  resource :users, only: %i(edit update)

  mount ActionCable.server => "/cable"

  resources :passwords, controller: "clearance/passwords", only: %i(create new)
  resource :session, controller: :sessions, only: :create

  resources :users, controller: "clearance/users", only: :create do
    resource :password, controller: "clearance/passwords",
                        only: %i(create edit update)
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include Chat::User
  include Clearance::User

  has_attached_file :image
  validates_attachment :image, content_type: {
    content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  }
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :require_login
  before_action :set_user, only: %i(edit update)

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to root_path, notice: "User was successfully updated."
    else
      render :edit
    end
  end

  private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(
      :first_name, :last_name, :image, :email, :password
    )
  end
end

app/views/users/edit.html.haml
= link_to root_path, class: "link-back" do
  = material_icon.arrow_back

.container
  %h1.mdc-theme--text-primary-on-primary Settings
  = form_for @user, url: users_path, method: :put do |f|
    = render 'clearance/users/form', f: f

    .mdc-textfield
      = f.text_field :first_name,
          class: "mdc-textfield__input mdc-theme--text-primary-on-primary",
          required: true
      = f.label :first_name, "First Name", class: "mdc-textfield__label"

    .mdc-textfield
      = f.text_field :last_name,
          class: "mdc-textfield__input mdc-theme--text-primary-on-primary",
          required: true
      = f.label :last_name, "Last Name", class: "mdc-textfield__label"

    = f.file_field :image, placeholder: 'Image'

    %button.mdc-button.mdc-button--primary{ type: :submit } Save

app/views/users/new.html.haml
= link_to sign_in_path, class: "link-back" do
  = material_icon.arrow_back

.container
  %h1.mdc-theme--text-primary-on-primary= t('.title')
  = form_for @user do |f|
    = render 'clearance/users/form', f: f

    %button.mdc-button.mdc-button--primary{ type: :submit } Sign Up